### ISSUE TITLE
Compilation failed，please help！！

### ISSUE THREAD

**Issue by lyuhaoxuan** [larryaasen/obslib-framework#1]
Undefined symbols for architecture x86_64:
  "_obs_audio_encoder_create", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_data_create", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_data_set_bool", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_data_set_default_bool", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_data_set_string", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_encoder_addref", referenced from:
      OBSRef<obs_encoder*, &(obs_encoder_addref), &(obs_encoder_release)>::OBSRef(obs_encoder*) in setup_obs.o
  "_obs_encoder_release", referenced from:
      OBSRef<obs_encoder*, &(obs_encoder_addref), &(obs_encoder_release)>::~OBSRef() in setup_obs.o
  "_obs_encoder_set_audio", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_encoder_set_video", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_get_audio", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_get_video", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_load_all_modules", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_output_addref", referenced from:
      OBSRef<obs_output*, &(obs_output_addref), &(obs_output_release)>::OBSRef(obs_output*) in setup_obs.o
  "_obs_output_create", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_output_release", referenced from:
      OBSRef<obs_output*, &(obs_output_addref), &(obs_output_release)>::~OBSRef() in setup_obs.o
  "_obs_output_set_audio_encoder", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_output_set_service", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_output_set_video_encoder", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_output_start", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_output_update", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_post_load_modules", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_reset_audio", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_reset_video", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_scene_add", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_scene_create", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_scene_get_source", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_scene_release", referenced from:
      OBSUniqueHandle<obs_scene, void (obs_scene*), &(obs_scene_release)>::OBSUniqueHandle(obs_scene*) in setup_obs.o
  "_obs_service_addref", referenced from:
      OBSRef<obs_service*, &(obs_service_addref), &(obs_service_release)>::OBSRef(obs_service*) in setup_obs.o
  "_obs_service_create", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_service_release", referenced from:
      OBSRef<obs_service*, &(obs_service_addref), &(obs_service_release)>::~OBSRef() in setup_obs.o
  "_obs_set_output_source", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_source_add_frame_callback", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_source_create", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_source_release", referenced from:
      OBSUniqueHandle<obs_source, void (obs_source*), &(obs_source_release)>::OBSUniqueHandle(obs_source*) in setup_obs.o
  "_obs_source_update", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_startup", referenced from:
      _CreateOBS in setup_obs.o
  "_obs_video_encoder_create", referenced from:
      _CreateOBS in setup_obs.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by larryaasen** [comment]
Can you provide more details?

**Comment by lyuhaoxuan** [comment]
Sorry, English is my weakness. Hope you can understand what I mean.

When I use **otool** to check dependency links. I found some places that I don't quite understand.

otool -L /.../obslib.framework/Versions/A/obslib
       @rpath/obslib.framework/Versions/A/obslib
        **#What seems to be missing in this place? For example: libobs.0.dylib**
	/System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
	/usr/lib/libSystem.B.dylib

otool -L /.../obslib.framework/Versions/A/Frameworks/libavcodec.58.dylib
        /tmp/obsdeps/lib/libavcodec.58.dylib  **<-- This is an absolute path.  @rpath ?**
	@rpath/libswresample.3.dylib
	@rpath/libavutil.56.dylib
	/usr/lib/libSystem.B.dylib
	/usr/lib/libiconv.2.dylib
	/usr/lib/libz.1.dylib
	/System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
	@rpath/libx264.161.dylib
	/System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
	/System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
	/System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices

There's some left ......

**Comment by larryaasen** [comment]
I think that issue is fixed. Try the update to the [Framework Alpha #1](https://github.com/larryaasen/obslib-framework/releases/tag/framework-alpha-1) release.

**Comment by larryaasen** [comment]
@lyuhaoxuan Did that work for you?

**Comment by lyuhaoxuan** [comment]
It is very helpful to me. thank you very much.
However, my APP has given up obs.
Sorry, I can’t give you any more feedback.
